export enum Atoms {
    Slug = "Slug",
    PageData = "PageData",
    Course = "Course",
    Class = "Class",
    Curriculum = "Curriculum",
    Creator = "Creator",
    Website = "Website",
    isEditor = "isEditor",
    UserId = "UserId",
    Lead = "Lead",
    StudentAuth = "StudentAuth",
    KohbeeStudent = "KohbeeStudent",
    KohbeeSession = "KohbeeSession",
    SourceUtm = "SourceUtm",
    KohbeeQuizAtom = "KohbeeQuizAtom",
    KohbeeAllQuestionsAtom = "KohbeeAllQuestionsAtom",
    KohbeeQuizQuestionAtom = "KohbeeQuizQuestionAtom",
    KohbeeQuizDetailsAtom = "KohbeeQuizDetailsAtom",
    KohbeeQuizSubmissionAtom = "KohbeeQuizSubmissionAtom",
    KohbeeQuizResultAtom = "KohbeeQuizResultAtom",
    PaymentPlan = "PaymentPlan",
    CourseNavigator = "CourseNavigator",
    Lessons = "Lessons",
    BackUrl = "BackUrl",
    KohbeeMarketingPoster = "KohbeeMarketingPoster",
}
